version: 1
formatters:
  base: 
    format: "[%(process)d:%(thread)d] [%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: base
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: base
    filename: ${hydra:runtime.output_dir}/output.log
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: False

# logThreads: False
# logProcesses: False
# logMultiprocessing: False

# Classes: StreamHandler, FileHandler, RotatingFileHandler, SysLogHandler, QueueHandler, NullHandler