defaults:
  - inputs: physnet_orientation
  - targets: physnet
  - outputs: physnet
  - predictions: physnet

resolve:
  inputs:
    input: ${datamodule.dataset.frames}
    output: inputs/traces
  targets:
    input: ${datamodule.dataset.labels}
  outputs:
    input: signal
  predictions:
    input: signal

frequencies: [0.70, 2.50]