# CSV Logger

# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.loggers.csv_logs.html#csv-logger

# ...

csv_logger:
  _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
  save_dir: ${paths.artifact_dir}/csv
  name: ${experiment}
  # version: 0
  # prefix: 
  # flush_logs_every_n_steps: 