# Device Statistics Monitor

# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.DeviceStatsMonitor.html#devicestatsmonitor

# if `None` will log CPU only if accelerator is CPU
# if `True` will log CPU regardless of accelerator
# if `False` will NOT log CPU regardless of accelerator

_target_: lightning.pytorch.callbacks.DeviceStatsMonitor
cpu_stats: None