# Early Stopping

# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html#earlystopping

# Monitor a metric and stop training once the condition is reach e.g. stopped improving
# Custom resolver ...

_target_: lightning.pytorch.callbacks.EarlyStopping

monitor: ${loss_name:train}
mode: min

min_delta: 0.01
patience: 10

#
check_finite: True # Stop training if val_loss if NaN or infinite
# stopping_threshold:
# divergence_threshold:
check_on_train_epoch_end: True

# Configuration
strict: True
verbose: True
log_rank_zero_only: True # Log on rank 0 process only