# MMPD Unsupervised Signal Processing Methods Conditions
# https://github.com/McJackTang/MMPD_rPPG_dataset#unsupervised-signal-processing-methodssubset

# Skin-tone Comparison
  # EXCLUDE exercise=True
  # EXCLUDE light=nature
  # EXCLUDE motion=walking

source:
  skip:
    _target_: src.datamodules.datapipes.sample.filters.FilterOut
    filters:
      # Exclusion criterion
      exclude_filter:
        _target_: src.datamodules.datapipes.sample.filters.ExcludeIfAnyIn
        match:
          motion: ["Walking"]
          light: ["Nature"]
          exercise: [True]