# Defaults
defaults:
  - default
  - _self_

# Source
# inputs:
#   _target_: src.datamodules.datasources.mmpd.MMPD_DatasetSource
#   roots:
#     _target_: src.datamodules.datasources.paths.mmpd.MMPD_Roots
#     # root: ${paths.data_dir}/vital_signs/MMPD/MMPD_full_processed
#     root: "${oc.env:DATA_ROOT}/MMPD/MMPD_full_reformatted"

# MMPD-formatted
# inputs:
#   _target_: src.datamodules.datasources.paths.Paths
#   root: ${oc.env:DATA_ROOT}/MMPD/MMPD_full_reformatted # input
#   regex: "*/video.avi"

# PURE
inputs:
  _target_: src.datamodules.datasources.paths.Paths
  root: ${paths.data_dir}/vital_signs/PURE_default/docs/pure/ForPublication/processed # Formatted publication images
  # root: ${paths.data_dir}/vital_signs/PURE_default/processed
  regex: "01-06/video.avi"

# Video Features
processes:
  _target_: src.datamodules.datapipes.DataPipe
  operations:
    # # Bounding Box Detection
    # bounding_box_detection:
    #   _target_: src.datamodules.datapipes.extract.ExtractFeaturesFromVideos
    #   extractor:
    #     _target_: src.datamodules.datapipes.extract.ExtractVideoFeatures
    #     model:
    #       _target_: src.datamodules.datapipes.extract.detection.HAARCascadeDetector
    #       path: ${paths.model_dir}/facial_detection/haarcascade_frontalface_default.xml
    #     skip_existing: True
    #   return_key: paths

    # # Bounding Box Interpolation
    # bounding_box_interpolation:
    #   _target_: src.datamodules.datapipes.extract.InterpolateDetectionsFromPaths
    #   interpolator:
    #     _target_: src.datamodules.datapipes.extract.detection.InterpolateBoundingBoxes
    #     key: haarcascade_frontalface_default # algorithm output to interpolate
    #     max_interpolate: 3 # 0.1s worth of video @ 30 FPS
    #     skip_existing: True
    #   return_key: paths
        
    # Landmark Detection
    landmark_detection:
      _target_: src.datamodules.datapipes.extract.ExtractFeaturesFromVideos
      extractor:
        _target_: src.datamodules.datapipes.extract.ExtractVideoFeatures
        model:
          _target_: src.datamodules.datapipes.extract.landmarks.MediaPipeLandmarkExtractor
          static_image_mode: False
          max_num_faces: 1
          refine_landmarks: True
          min_detection_confidence: 0.45
          min_tracking_confidence: 0.45
        skip_existing: True
      return_key: paths
    
    # Landmark Interpolation
    landmark_interpolation:
      _target_: src.datamodules.datapipes.extract.InterpolateDetectionsFromPaths
      interpolator:
        _target_: src.datamodules.datapipes.extract.landmarks.InterpolateLandmarks
        max_interpolate: 3 # 0.1s worth of video
        skip_existing: True
      return_key: paths
