# Defaults
defaults:
  - default
  - _self_

# Source dataset
inputs:
  _target_: src.datamodules.datasources.paths.Paths
  root: ${paths.data_dir}/PURE-formatted
  regex: "*/" # Subject 1 / Scenario 1
  process:
    _target_: src.datamodules.datasources.pure.PURE_DataSample
    detections: FaceDetector_FaceMeshV2_landmarks.HDF5
    _partial_: True

# Dataset pre-processing
processes:
  _target_: src.datamodules.datapipes.DataPipe
  operations:
    construct_samples:
      _target_: src.datamodules.datapipes.sample.construct.ProcessDatasetSamples
      filenames:
        video:
          inputs/frames: null # default # PURE uses FRAMES_FOLDER not VIDEO.AVI
        detections:
          detections/landmarks: null # default
      use_detections: True # slice frames for available detections
      fkey: inputs/frames
      dkey: detections/landmarks
      process:
        _target_: src.datamodules.datapipes.DataPipe
        operations:
          compute_uv:
            _target_: src.datamodules.datapipes.transform.frames.ComputeFramesAndAnglesUV
            fkey: inputs/frames
            dkey: detections/landmarks
            frames_okey: outputs/frames_uv
            angles_okey: outputs/angles_uv
            size: 128
            fill: 0.0 # angle fill since dp is scaled to [0,1] after calculation (maybe not ideal...)
          export_frames_uv:
            _target_: src.datamodules.datapipes.format.ExportSlicedVideoFrames
            key: outputs/frames_uv
            dkey: detections/landmarks
            dirname: frames_uv
            size: 128 # necessary to create empty frames for missing landmarks... 
          export_angles_uv:
            _target_: src.datamodules.datapipes.format.ExportSlicedVideoFrames
            key: outputs/angles_uv
            dkey: detections/landmarks
            dirname: angles_uv
            size: 128
          export_landmarks_uv:
            _target_: src.datamodules.datapipes.format.ExportLandmarks
            key: detections/landmarks_uv
            filename: UV_${inputs.process.detections} # appended to existing fileloc
