# Defaults
defaults:
  - default
  - _self_
  - split/subjects@_here_

# Target
_target_: src.datamodules.datasets.pure.PURE_Dataset
name: PURE

# Keys : useful for referencing in model config
frames: inputs/frames
labels: targets/labels

# Detections
detections: FaceDetector_FaceMeshV2_landmarks.HDF5

# Filenames
filenames:
  video:
    inputs/frames: null
  bvp:
    targets/labels: bvp_resampled.HDF5 # re-sampled to video timestamps (irregular though)
  detections:
    detections/landmarks: null # default (see above)
  metadata:
    source/sample: null

# Cache
cache: null #${oc.env:DATA_ROOT}/PURE/cache/${oc.env:MLFLOW_RUN_UUID,"experiment"}

# Source
source:
  _target_: src.datamodules.datasources.paths.Paths
  root: ${paths.data_dir}/vital_signs/PURE_default/processed
  regex: "*/"
  process:
    _target_: src.datamodules.datasources.pure.PURE_DataSample
    detections: ${datamodule.dataset.detections} # assign default detection file
    _partial_: True

# Samples
construct:
  _target_: src.datamodules.datapipes.DataPipe
  operations: 
    construct_dataset_samples:
      _target_: src.datamodules.datapipes.sample.construct.GenerateFrameSlices
      window: ${model.network.window}
      stride: null
      return_key: samples # Dict[int, SampleAttrs]

# Process
process:
  _target_: src.datamodules.datapipes.DataPipe
  operations: # Appended with model-specific processes 
    prepare:
      _target_: src.datamodules.datapipes.transform.ToPrepared
    to_float: 
      _target_: src.datamodules.datapipes.transform.frames.ToFloat # to [0-1|FP32]
      fkey: inputs/frames
      max_value: 255
    to_tensor:
      _target_: src.datamodules.datapipes.transform.ToTensor # to tensor

# # Augmentations
# augment:
#   _target_: src.datamodules.datapipes.DataPipe
#   operations:
#     horizontal_flip:
#       _target_: src.datamodules.datapipes.augment.HorizontalFlipVideo
#       fkey: inputs/frames
#       dkey: detections/landmarks
#       always_apply_video: False
#       p_video: 0.50
#       always_apply_frame: True
#       per_video: True
#     rotate:
#       _target_: src.datamodules.datapipes.augment.RotateVideo
#       fkey: inputs/frames
#       dkey: detections/landmarks
#       always_apply_video: False
#       p_video: 0.50
#       always_apply_frame: True
#       per_video: True
#       aug_args:
#         limit: [-15, 15]
