# Model Checkpointing

# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html#modelcheckpoint

# 

_target_: lightning.pytorch.callbacks.ModelCheckpoint

# Location
dirpath: ${hydra:runtime.output_dir}
filename: latest

# Timing
# every_n_train_steps: # use this when performing iterative non-epoch based training
# train_time_interval:
every_n_epochs: 1
save_on_train_epoch_end: True

# Metric
# monitor: valid_loss
# mode: min

# Model
# save_last: False
# save_top_k: 1
# save_weights_only: True

# Information
# auto_insert_metric_name:
# enable_version_counter: False
verbose: False